#!/bin/bash
source ${shell_script_loc}/workFlowUtil.sh
finishTaskTimeStamp=1702307510
projectName=酒仙官网app
taskTypeNameAbbreviation=fix
taskTypeIndex=
createBranchFlag=Y
productManager=周立新
developer=付玉光
tester=田玲玲
taskName=testttt
branchVersion=9.1.20
mateDataCreateDate=2023-12-11
mateDataCreateTaskHourMinuteSecond=22-09-30
workDir=/酒仙官网app/9.1.20/2023-12-11--19-02-43_付玉光___feat_33333/子任务/2023-12-11--19-08-33_付玉光___feat_555/子任务/2023-12-11--22-09-30_付玉光_Y_fix_testttt
#workDir=/Users/fuyuguang/jiuxian_studio/doc/1版本/酒仙官网app/9.1.20/2023-12-11--19-02-43_付玉光___feat_33333/子任务/2023-12-11--19-08-33_付玉光___feat_555/子任务/2023-12-11--22-09-30_付玉光_Y_fix_testttt
branchName=feature/feature_fyg_9.1.20_testttt
preReleaseBranchName=feature/feature_preRelease_9.1.20
renamedFeatureBranchName=
createTaskTime=2023-12-11/22-09-41
emailFileName=test_email.md
createTestEmailScriptName=appendTestEmail.sh
changedFileList=changedFileList.txt
main=develop
#gitProjectRootPath=/Users/fuyuguang/jiuxian_studio
showPatchDetails=false
isCreateBranch=true
generateFileChangedListScriptFile=listChangedFile.sh
generateRenameBranchScriptFile=renamedBranchScriptFile.sh
generateDeleteFeatureBranchScriptFile=deleteFeatureBranch.sh
projectMetaData=metaData.txt
taskDescriptionFile=testttt.md
#开发人员名单
developerGroup=/酒仙官网app/DeveloperGroup.txt
#测试人员名单
testerGroup=/酒仙官网app/TesterGroup.txt
#产品人员名单
productManagerGroup=/酒仙官网app/ProductManagerGroup.txt
#创建分支映射表
branchMapTable=/酒仙官网app/branchCreateTimeMapTable.txt
#项目元数据目录
projectMetaDataVersionList=/酒仙官网app/version_list.txt
#临时的父级任务列表文件
temTaskListFilePath=/酒仙官网app/tem/taskList/taskList.txt
#任务组层级
taskHierarchyGroup=/酒仙官网app/TaskHierarchyGroup.txt
taskHierarchyNameAbbreviation=level_2
#项目临时数据存放目录
projectTemDir=/酒仙官网app/tem
metaDataFileName=metaData.sh
changeScopeRelativePath=table/变更影响范围.md
taskDescribeRelativePath=table/描述.md
taskDesc=
changeScope=
metaDataPath=$(getFullDirectoryPath ${workDir} ${taskWorkDirParentLoc})/${metaDataFileName}
metaDataActionConsole ${metaDataPath}

