#!/bin/bash
source ${shell_script_loc}/workFlowUtil.sh
preReleaseBranchName=feature/feature_preRelease_9.1.20
branchName=feature/feature_ld_9.1.20_test33333
workDir=/酒仙官网app/9.1.20/2023-12-11--19-02-43_付玉光___feat_33333/子任务/2023-12-11--19-08-33_付玉光___feat_555/子任务/2023-12-11--23-11-27_刘丹___feat_test33333
taskDescriptionFile=test33333.md
taskName=test33333
developer=刘丹
taskHierarchyNameAbbreviation=level_2
branchVersion=9.1.20
finishTaskTimeStamp=1702307510
projectName=酒仙官网app
taskTypeNameAbbreviation=feat
taskTypeIndex=
createBranchFlag=_
productManager=张树静
tester=
mateDataCreateDate=2023-12-11
mateDataCreateTaskHourMinuteSecond=23-11-27
renamedFeatureBranchName=
createTaskTime=2023-12-11/23-11-33
emailFileName=test_email.md
createTestEmailScriptName=appendTestEmail.sh
changedFileList=changedFileList.txt
main=develop
#gitProjectRootPath=/Users/fuyuguang/jiuxian_studio
showPatchDetails=false
isCreateBranch=false
generateFileChangedListScriptFile=listChangedFile.sh
generateRenameBranchScriptFile=renamedBranchScriptFile.sh
generateDeleteFeatureBranchScriptFile=deleteFeatureBranch.sh
projectMetaData=metaData.txt
#开发人员名单
developerGroup=/酒仙官网app/DeveloperGroup.txt
#测试人员名单
testerGroup=/酒仙官网app/TesterGroup.txt
#产品人员名单
productManagerGroup=/酒仙官网app/ProductManagerGroup.txt
#创建分支映射表
branchMapTable=/酒仙官网app/branchCreateTimeMapTable.txt
#项目元数据目录
projectMetaDataVersionList=/酒仙官网app/version_list.txt
#临时的父级任务列表文件
temTaskListFilePath=/酒仙官网app/tem/taskList/taskList.txt
#任务组层级
taskHierarchyGroup=/酒仙官网app/TaskHierarchyGroup.txt
#项目临时数据存放目录
projectTemDir=/酒仙官网app/tem
metaDataFileName=metaData.sh
changeScopeRelativePath=table/变更影响范围.md
taskDescribeRelativePath=table/描述.md
taskDesc=
changeScope=
metaDataPath=$(getFullDirectoryPath ${workDir} ${taskWorkDirParentLoc})/${metaDataFileName}
metaDataActionConsole ${metaDataPath}

